# Generated by Django 2.0 on 2018-07-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default="We at the shop offer you wide range of electronics from various seller across the world so<br> you can chose product at it's <b>Best Price</b>", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='home/ubox79/Downloads/logo.jpg', upload_to='media'),
        ),
    ]
