# Generated by Django 2.0 on 2018-07-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20180717_0815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
